name: update
on:
  push:
    branches: ["firebase"]

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Publish update
        run: |
          if ! eas update --auto; then
            echo "EAS Update failed on first attempt, retrying..."
            if ! eas update --auto; then
              echo "EAS Update failed again"
              exit 1
            fi
          fi

      - name: Build android
        run: eas build -p android --profile production || echo "Android build failed"
      
      - name: Build ios
        run: eas build -p ios --profile production || echo "iOS build failed"

